// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251220143717_AddHistoryPpa")]
    partial class AddHistoryPpa
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Ppa.Entities.PpaHistoryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ActionType")
                        .HasColumnType("integer");

                    b.Property<string>("NewValue")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("OldValue")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("PerformedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PerformedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PpaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PerformedAt")
                        .HasDatabaseName("IX_PpaHistoryEntries_PerformedAt");

                    b.HasIndex("PerformedByUserId")
                        .HasDatabaseName("IX_PpaHistoryEntries_PerformedByUserId");

                    b.HasIndex("PpaId")
                        .HasDatabaseName("IX_PpaHistoryEntries_PpaId");

                    b.HasIndex("PpaId", "ActionType")
                        .HasDatabaseName("IX_PpaHistoryEntries_PpaId_ActionType");

                    b.ToTable("PpaHistoryEntries", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.Academics.AcademicPeriodEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_AcademicPeriods_Code");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_AcademicPeriods_IsActive");

                    b.HasIndex("StartDate", "EndDate")
                        .HasDatabaseName("IX_AcademicPeriods_Dates");

                    b.ToTable("AcademicPeriods", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.Academics.SubjectEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_Subjects_Code");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Subjects_IsActive");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Subjects_Name");

                    b.ToTable("Subjects", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("589b6945-2dae-1b3e-3a2b-ffd185c16b27"),
                            Code = "125-0703",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "FORMULACION Y EVALUACION DE PROYECTOS",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("3c24ed93-c383-87c6-f420-4f52ea8d1692"),
                            Code = "125-0744",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "METODOS NUMERICOS",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("db1c982a-6d90-e25a-c1a1-320b3331bc17"),
                            Code = "125-0747",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "ACCESIBILIDAD Y USABILIDAD",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("76094584-b2cf-b2e8-2381-0cd74bcecac0"),
                            Code = "125-0750",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "DISEÑO MOVIL",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("407819d6-02a4-1d37-794e-f7b04152e545"),
                            Code = "125-0745",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "INVESTIGACION DE OPERACIONES",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("ec385ffc-e50b-598e-eb32-e0a2d025642e"),
                            Code = "125-0748",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "TECNOLOGIAS EMERGENTES",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("a08ae93d-f6c3-90f1-f26c-8a91bdeabf21"),
                            Code = "125-0751",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "DISEÑO FUNCIONAL",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("dac58feb-ab18-748c-25ff-58997afe01b1"),
                            Code = "125-0753",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "GESTION DE PROYECTOS DE SOFTWARE",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("bd6c7108-833e-d420-15bb-7a80fe9cc141"),
                            Code = "125-0746",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "TEORIA DE DECISIONES",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("7cca5530-eb02-4dd6-ce73-6aa0cc4f8d63"),
                            Code = "125-0749",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "INTELIGENCIA ARTIFICIAL",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("fab0d1ca-e941-16c1-5f64-b236f5a55440"),
                            Code = "125-0752",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "DISEÑO MULTIMEDIA Y VIDEOJUEGOS",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("703349a9-3411-8e41-b9c2-58d3107c7df2"),
                            Code = "125-0754",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "CALIDAD Y SEGURIDAD DEL SOFTWARE",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("ad9afd67-2927-4c6e-920d-777dfc341ab7"),
                            Code = "125-1077",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "PRACTICA EMPRESARIAL EMPRESARIAL",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("17ffa3fd-70b8-387f-91bd-00e39fc72f8c"),
                            Code = "124-0613",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "CATEDRA FESC, CULTURA Y VALORES",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("5997ccd5-4b36-5cf5-b7a5-91170d49e558"),
                            Code = "124-0715",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "ELECTRONICA DIGITAL",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("cc0f1826-8069-381b-8aa6-fe9b0aa411e4"),
                            Code = "124-0722",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "ENSAMBLE Y MANTENIMIENTO DE COMPUTADORES",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("45c27cc6-a6e1-981d-86cf-2f8fee5029e0"),
                            Code = "124-0726",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "LOGICA Y FUNDAMENTOS DE PROGRAMACION",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("d2a2acce-7e0c-2f72-c678-85ef7da31698"),
                            Code = "124-0731",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "INTRODUC A LA INGENIERIA DEL SOFTWARE",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("dd97c328-87a0-8922-3fbf-41e623543786"),
                            Code = "124-7022",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "HABILIDADES COMUNICATIVAS",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("8b53cdc8-7f9f-e465-6376-8423dca61314"),
                            Code = "124-0716",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "FISICA MECANICA",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("6590fd8c-f623-1b33-7dba-54cc32b7eec2"),
                            Code = "124-0718",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "CALCULO DIFERENCIAL",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("a294b1a7-cb3e-9c38-fc68-94d15e7e2389"),
                            Code = "124-0723",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "INSTALACION Y CONFIGURACION DE REDES",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("977dc821-4277-fa2c-b181-087f4698d03e"),
                            Code = "124-0727",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "PROGRAMACION ESTRUCTURADA",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("5e2fd604-e12f-e129-e8a9-cbf4b5ac4024"),
                            Code = "124-0732",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "METODOLOGIAS DESARROLLO DEL SOFTWARE",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("2a836363-74ba-f2a1-b9b2-b68abd4e59c9"),
                            Code = "124-3024",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "EMPRENDIMIENTO",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("cd75b1e7-1fb6-db58-b149-c3f127531fc8"),
                            Code = "124-0069",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "PRODUCCION Y ANALISIS DE TEXTOS",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("9cdd082c-c6ca-914f-bc28-d313825b11b9"),
                            Code = "124-0717",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "FISICA ELECTROMAGNETICA",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("d9b42b42-8a22-1e32-1b8c-34d2f041af6f"),
                            Code = "124-0719",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "CALCULO INTEGRAL",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("d6861d03-0d01-8dee-7c04-b7398f4e0559"),
                            Code = "124-0724",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "OFIMATICA, REDES SOCIALES Y COLABORATIVA",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("2063ad81-2b78-6fdc-55e0-5fd70ecc6c8a"),
                            Code = "124-0733",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "MODELOS Y DOCUMENTACION DEL SOFTWARE",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("4d0d252e-febb-8bbc-b705-a5b90d4a89c7"),
                            Code = "124-0741",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "BASE DE DATOS",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("767457a1-8dce-0706-b493-bfaf75ab27a8"),
                            Code = "124-8047",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "INVESTIGACION DE MERCADOS",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("f77b466c-1dd8-2ab6-b35f-7277e9e07f10"),
                            Code = "124-I-01",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "INGLES A1:1",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("aa5caf57-85d2-dad8-e34e-16faedea6913"),
                            Code = "124-0082",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "CONTABILIDAD Y COSTOS",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("06349c30-3880-a261-ea8b-cc01cff8f647"),
                            Code = "124-0720",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "ALGEBRA LINEAL",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("254c6e53-37df-de3f-0258-719148e91956"),
                            Code = "124-0725",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "SISTEMAS OPERATIVOS",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("1c6d2287-2bac-434d-60d0-356e205585c9"),
                            Code = "124-0728",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "PROGRAMACION ORIENTADA A OBJETOS",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("f2894310-a209-b756-a547-b3268bbfb67b"),
                            Code = "124-0736",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "ELECTIVA I",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("8d890004-277c-2471-8e18-21310b663799"),
                            Code = "124-0742",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "ANALISIS DE RQUERIMIENTOS DEL SOFTWARE",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00ccb6b6-8d31-e7be-987f-c608d6317abf"),
                            Code = "124-I-02",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "INGLES A1:2",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("6ca9081a-19fc-dfbb-321b-9a9021b8350d"),
                            Code = "124-0071",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "PLAN DE NEGOCIOS",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("fb61df01-dd77-c74e-91d9-609548c0ca69"),
                            Code = "124-0721",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "CALCULO MULTIVARIADO",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("1616574f-71a3-f049-e656-d7ea3414c109"),
                            Code = "124-0729",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "DESARROLLO BASICO APLICACIONES EN RED",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("36fbad24-a3dc-11aa-9f56-cb703a2c50ba"),
                            Code = "124-0734",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "ARQUITECTURA Y DISEÑO DEL SOFTWARE",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50d6753b-4431-fd06-8b88-f7f3dd2f2c7d"),
                            Code = "124-0743",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "ESTADISTICA Y PROBABILIDAD",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("2cfcc659-3a17-7fb6-cb2f-bb374705bbc9"),
                            Code = "124-0779",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "ARQUITECTURA CLIENTE SERVIDOR - Propedeu",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("ddd79bb1-a388-6cca-fdf3-6386da149c6c"),
                            Code = "124-8033",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "METODOLOGIA DE LA INVESTIGACION",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50410699-e483-2ee3-a7fb-b4ca1395c3d8"),
                            Code = "124-I-03",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "INGLES A2:1",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("beba8df3-fc30-5a4f-fc91-b085b981f806"),
                            Code = "124-0730",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "DESARROLLO AVANZADO APLICACIONES EN RED",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("f6778165-dadc-4b14-4694-2bfcd7af0e3a"),
                            Code = "124-0735",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "CODIFICACION Y PRUEBAS DEL SOFTWARE",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("04a14d1a-110c-da5b-9410-2a5a008b677f"),
                            Code = "124-0737",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "ELECTIVA II",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("e480a49b-24f0-9507-6f4b-b98ec85e18f0"),
                            Code = "124-0820",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "ECUACIONES DIFERENCIALES",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("16b71051-0257-a6bb-6b12-3cfc395feb59"),
                            Code = "124-1076",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "PRACTICA EMPRESARIAL",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.Academics.TeacherAssignmentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AcademicPeriodId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AcademicPeriodId")
                        .HasDatabaseName("IX_TeacherAssignments_AcademicPeriodId");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_TeacherAssignments_IsActive");

                    b.HasIndex("SubjectId")
                        .HasDatabaseName("IX_TeacherAssignments_SubjectId");

                    b.HasIndex("TeacherId")
                        .HasDatabaseName("IX_TeacherAssignments_TeacherId");

                    b.HasIndex("TeacherId", "SubjectId", "AcademicPeriodId")
                        .IsUnique()
                        .HasDatabaseName("IX_TeacherAssignments_Unique");

                    b.ToTable("TeacherAssignments", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.PermissionEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_Permissions_Code");

                    b.HasIndex("Module", "Action")
                        .HasDatabaseName("IX_Permissions_Module_Action");

                    b.ToTable("Permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Action = "view",
                            Code = "periods.view",
                            Description = "Ver períodos académicos",
                            Module = "periods"
                        },
                        new
                        {
                            Id = 2L,
                            Action = "create",
                            Code = "periods.create",
                            Description = "Crear períodos académicos",
                            Module = "periods"
                        },
                        new
                        {
                            Id = 3L,
                            Action = "update",
                            Code = "periods.update",
                            Description = "Actualizar períodos académicos",
                            Module = "periods"
                        },
                        new
                        {
                            Id = 4L,
                            Action = "deactivate",
                            Code = "periods.deactivate",
                            Description = "Desactivar períodos académicos",
                            Module = "periods"
                        },
                        new
                        {
                            Id = 5L,
                            Action = "view",
                            Code = "subjects.view",
                            Description = "Ver materias/asignaturas",
                            Module = "subjects"
                        },
                        new
                        {
                            Id = 6L,
                            Action = "create",
                            Code = "subjects.create",
                            Description = "Crear materias/asignaturas",
                            Module = "subjects"
                        },
                        new
                        {
                            Id = 7L,
                            Action = "update",
                            Code = "subjects.update",
                            Description = "Actualizar materias/asignaturas",
                            Module = "subjects"
                        },
                        new
                        {
                            Id = 8L,
                            Action = "deactivate",
                            Code = "subjects.deactivate",
                            Description = "Desactivar materias/asignaturas",
                            Module = "subjects"
                        },
                        new
                        {
                            Id = 9L,
                            Action = "manage",
                            Code = "teacherSubjects.manage",
                            Description = "Gestionar asignación docente-materia",
                            Module = "teacherSubjects"
                        },
                        new
                        {
                            Id = 10L,
                            Action = "view_all",
                            Code = "ppa.view_all",
                            Description = "Ver todos los PPAs",
                            Module = "ppa"
                        },
                        new
                        {
                            Id = 11L,
                            Action = "view_own",
                            Code = "ppa.view_own",
                            Description = "Ver sus propios PPAs",
                            Module = "ppa"
                        },
                        new
                        {
                            Id = 12L,
                            Action = "create",
                            Code = "ppa.create",
                            Description = "Crear PPAs",
                            Module = "ppa"
                        },
                        new
                        {
                            Id = 13L,
                            Action = "update",
                            Code = "ppa.update",
                            Description = "Actualizar PPAs",
                            Module = "ppa"
                        },
                        new
                        {
                            Id = 14L,
                            Action = "change_status",
                            Code = "ppa.change_status",
                            Description = "Cambiar estado de PPAs",
                            Module = "ppa"
                        },
                        new
                        {
                            Id = 15L,
                            Action = "upload_file",
                            Code = "ppa.upload_file",
                            Description = "Subir archivos a PPAs",
                            Module = "ppa"
                        },
                        new
                        {
                            Id = 16L,
                            Action = "view_all",
                            Code = "resources.view_all",
                            Description = "Ver todos los recursos",
                            Module = "resources"
                        },
                        new
                        {
                            Id = 17L,
                            Action = "view_own",
                            Code = "resources.view_own",
                            Description = "Ver sus propios recursos",
                            Module = "resources"
                        },
                        new
                        {
                            Id = 18L,
                            Action = "create",
                            Code = "resources.create",
                            Description = "Crear recursos",
                            Module = "resources"
                        },
                        new
                        {
                            Id = 19L,
                            Action = "update",
                            Code = "resources.update",
                            Description = "Actualizar recursos",
                            Module = "resources"
                        },
                        new
                        {
                            Id = 20L,
                            Action = "delete",
                            Code = "resources.delete",
                            Description = "Eliminar recursos",
                            Module = "resources"
                        },
                        new
                        {
                            Id = 21L,
                            Action = "view",
                            Code = "dashboard.view",
                            Description = "Ver dashboard",
                            Module = "dashboard"
                        },
                        new
                        {
                            Id = 22L,
                            Action = "view_details",
                            Code = "dashboard.view_details",
                            Description = "Ver detalles del dashboard",
                            Module = "dashboard"
                        });
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.Ppa.PpaAttachmentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("PpaId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FileKey")
                        .IsUnique()
                        .HasDatabaseName("IX_PpaAttachments_FileKey");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_PpaAttachments_IsDeleted");

                    b.HasIndex("PpaId")
                        .HasDatabaseName("IX_PpaAttachments_PpaId");

                    b.HasIndex("Type")
                        .HasDatabaseName("IX_PpaAttachments_Type");

                    b.HasIndex("UploadedByUserId")
                        .HasDatabaseName("IX_PpaAttachments_UploadedByUserId");

                    b.HasIndex("PpaId", "Type")
                        .HasDatabaseName("IX_PpaAttachments_Ppa_Type");

                    b.ToTable("PpaAttachments", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.Ppa.PpaEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AcademicPeriodId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)");

                    b.Property<string>("GeneralObjective")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("PrimaryTeacherId")
                        .HasColumnType("uuid");

                    b.Property<string>("SpecificObjectives")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AcademicPeriodId")
                        .HasDatabaseName("IX_Ppas_AcademicPeriodId");

                    b.HasIndex("PrimaryTeacherId")
                        .HasDatabaseName("IX_Ppas_PrimaryTeacherId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Ppas_Status");

                    b.HasIndex("PrimaryTeacherId", "AcademicPeriodId")
                        .HasDatabaseName("IX_Ppas_Teacher_Period");

                    b.ToTable("Ppas", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.Ppa.PpaTeacherAssignmentEntity", b =>
                {
                    b.Property<Guid>("PpaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeacherAssignmentId")
                        .HasColumnType("uuid");

                    b.HasKey("PpaId", "TeacherAssignmentId");

                    b.HasIndex("PpaId")
                        .HasDatabaseName("IX_PpaTeacherAssignments_PpaId");

                    b.HasIndex("TeacherAssignmentId")
                        .HasDatabaseName("IX_PpaTeacherAssignments_TeacherAssignmentId");

                    b.ToTable("PpaTeacherAssignments", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.RoleEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsSystemRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_Roles_Code");

                    b.HasIndex("IsSystemRole")
                        .HasDatabaseName("IX_Roles_IsSystemRole");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Code = "ADMIN",
                            Description = "Acceso completo a gestión académica (períodos, materias, asignaciones), supervisión de PPAs y dashboard completo.",
                            IsSystemRole = true,
                            Name = "Administrador"
                        },
                        new
                        {
                            Id = 2L,
                            Code = "DOCENTE",
                            Description = "Gestiona sus propios PPAs y recursos académicos, visualiza materias asignadas.",
                            IsSystemRole = true,
                            Name = "Docente"
                        },
                        new
                        {
                            Id = 3L,
                            Code = "CONSULTA_INTERNA",
                            Description = "Acceso de solo lectura para consulta y auditoría de PPAs, recursos y dashboard.",
                            IsSystemRole = true,
                            Name = "Consulta Interna"
                        });
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.RolePermissionEntity", b =>
                {
                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.Property<long>("PermissionId")
                        .HasColumnType("bigint");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId")
                        .HasDatabaseName("IX_RolePermissions_PermissionId");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("IX_RolePermissions_RoleId");

                    b.ToTable("RolePermissions", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 1L
                        },
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 2L
                        },
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 3L
                        },
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 4L
                        },
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 5L
                        },
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 6L
                        },
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 7L
                        },
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 8L
                        },
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 9L
                        },
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 10L
                        },
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 13L
                        },
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 14L
                        },
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 15L
                        },
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 16L
                        },
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 21L
                        },
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 22L
                        },
                        new
                        {
                            RoleId = 2L,
                            PermissionId = 5L
                        },
                        new
                        {
                            RoleId = 2L,
                            PermissionId = 11L
                        },
                        new
                        {
                            RoleId = 2L,
                            PermissionId = 12L
                        },
                        new
                        {
                            RoleId = 2L,
                            PermissionId = 13L
                        },
                        new
                        {
                            RoleId = 2L,
                            PermissionId = 14L
                        },
                        new
                        {
                            RoleId = 2L,
                            PermissionId = 15L
                        },
                        new
                        {
                            RoleId = 2L,
                            PermissionId = 17L
                        },
                        new
                        {
                            RoleId = 2L,
                            PermissionId = 18L
                        },
                        new
                        {
                            RoleId = 2L,
                            PermissionId = 19L
                        },
                        new
                        {
                            RoleId = 2L,
                            PermissionId = 20L
                        },
                        new
                        {
                            RoleId = 3L,
                            PermissionId = 10L
                        },
                        new
                        {
                            RoleId = 3L,
                            PermissionId = 16L
                        },
                        new
                        {
                            RoleId = 3L,
                            PermissionId = 21L
                        },
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 12L
                        },
                        new
                        {
                            RoleId = 3L,
                            PermissionId = 1L
                        },
                        new
                        {
                            RoleId = 3L,
                            PermissionId = 5L
                        },
                        new
                        {
                            RoleId = 2L,
                            PermissionId = 1L
                        },
                        new
                        {
                            RoleId = 2L,
                            PermissionId = 21L
                        },
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 18L
                        },
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 19L
                        },
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 20L
                        });
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Email");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Users_IsActive");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@sigepp.local",
                            IsActive = true,
                            Name = "Administrador SIGEPP",
                            PasswordHash = "$2a$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewY5GyYIr.5gPyOu",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.UserRoleEntity", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("IX_UserRoles_RoleId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_UserRoles_UserId");

                    b.ToTable("UserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000001"),
                            RoleId = 1L
                        });
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.Academics.TeacherAssignmentEntity", b =>
                {
                    b.HasOne("Infrastructure.Persistence.Entities.Academics.AcademicPeriodEntity", "AcademicPeriod")
                        .WithMany("TeacherAssignments")
                        .HasForeignKey("AcademicPeriodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Infrastructure.Persistence.Entities.Academics.SubjectEntity", "Subject")
                        .WithMany("TeacherAssignments")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Infrastructure.Persistence.Entities.UserEntity", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AcademicPeriod");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.Ppa.PpaAttachmentEntity", b =>
                {
                    b.HasOne("Infrastructure.Persistence.Entities.Ppa.PpaEntity", "Ppa")
                        .WithMany("Attachments")
                        .HasForeignKey("PpaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infrastructure.Persistence.Entities.UserEntity", "UploadedBy")
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ppa");

                    b.Navigation("UploadedBy");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.Ppa.PpaEntity", b =>
                {
                    b.HasOne("Infrastructure.Persistence.Entities.Academics.AcademicPeriodEntity", "AcademicPeriod")
                        .WithMany()
                        .HasForeignKey("AcademicPeriodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Infrastructure.Persistence.Entities.UserEntity", "PrimaryTeacher")
                        .WithMany()
                        .HasForeignKey("PrimaryTeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AcademicPeriod");

                    b.Navigation("PrimaryTeacher");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.Ppa.PpaTeacherAssignmentEntity", b =>
                {
                    b.HasOne("Infrastructure.Persistence.Entities.Ppa.PpaEntity", "Ppa")
                        .WithMany("PpaTeacherAssignments")
                        .HasForeignKey("PpaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infrastructure.Persistence.Entities.Academics.TeacherAssignmentEntity", "TeacherAssignment")
                        .WithMany()
                        .HasForeignKey("TeacherAssignmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ppa");

                    b.Navigation("TeacherAssignment");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.RolePermissionEntity", b =>
                {
                    b.HasOne("Infrastructure.Persistence.Entities.PermissionEntity", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infrastructure.Persistence.Entities.RoleEntity", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.UserRoleEntity", b =>
                {
                    b.HasOne("Infrastructure.Persistence.Entities.RoleEntity", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Infrastructure.Persistence.Entities.UserEntity", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.Academics.AcademicPeriodEntity", b =>
                {
                    b.Navigation("TeacherAssignments");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.Academics.SubjectEntity", b =>
                {
                    b.Navigation("TeacherAssignments");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.PermissionEntity", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.Ppa.PpaEntity", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("PpaTeacherAssignments");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.RoleEntity", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.UserEntity", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
