// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251218222852_AddPpaModule")]
    partial class AddPpaModule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Infrastructure.Persistence.Entities.Academics.AcademicPeriodEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_AcademicPeriods_Code");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_AcademicPeriods_IsActive");

                    b.HasIndex("StartDate", "EndDate")
                        .HasDatabaseName("IX_AcademicPeriods_Dates");

                    b.ToTable("AcademicPeriods", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.Academics.SubjectEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_Subjects_Code");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Subjects_IsActive");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Subjects_Name");

                    b.ToTable("Subjects", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.Academics.TeacherAssignmentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AcademicPeriodId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AcademicPeriodId")
                        .HasDatabaseName("IX_TeacherAssignments_AcademicPeriodId");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_TeacherAssignments_IsActive");

                    b.HasIndex("SubjectId")
                        .HasDatabaseName("IX_TeacherAssignments_SubjectId");

                    b.HasIndex("TeacherId")
                        .HasDatabaseName("IX_TeacherAssignments_TeacherId");

                    b.HasIndex("TeacherId", "SubjectId", "AcademicPeriodId")
                        .IsUnique()
                        .HasDatabaseName("IX_TeacherAssignments_Unique");

                    b.ToTable("TeacherAssignments", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.PermissionEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_Permissions_Code");

                    b.HasIndex("Module", "Action")
                        .HasDatabaseName("IX_Permissions_Module_Action");

                    b.ToTable("Permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Action = "view",
                            Code = "periods.view",
                            Description = "Ver períodos académicos",
                            Module = "periods"
                        },
                        new
                        {
                            Id = 2L,
                            Action = "create",
                            Code = "periods.create",
                            Description = "Crear períodos académicos",
                            Module = "periods"
                        },
                        new
                        {
                            Id = 3L,
                            Action = "update",
                            Code = "periods.update",
                            Description = "Actualizar períodos académicos",
                            Module = "periods"
                        },
                        new
                        {
                            Id = 4L,
                            Action = "deactivate",
                            Code = "periods.deactivate",
                            Description = "Desactivar períodos académicos",
                            Module = "periods"
                        },
                        new
                        {
                            Id = 5L,
                            Action = "view",
                            Code = "subjects.view",
                            Description = "Ver materias/asignaturas",
                            Module = "subjects"
                        },
                        new
                        {
                            Id = 6L,
                            Action = "create",
                            Code = "subjects.create",
                            Description = "Crear materias/asignaturas",
                            Module = "subjects"
                        },
                        new
                        {
                            Id = 7L,
                            Action = "update",
                            Code = "subjects.update",
                            Description = "Actualizar materias/asignaturas",
                            Module = "subjects"
                        },
                        new
                        {
                            Id = 8L,
                            Action = "deactivate",
                            Code = "subjects.deactivate",
                            Description = "Desactivar materias/asignaturas",
                            Module = "subjects"
                        },
                        new
                        {
                            Id = 9L,
                            Action = "manage",
                            Code = "teacherSubjects.manage",
                            Description = "Gestionar asignación docente-materia",
                            Module = "teacherSubjects"
                        },
                        new
                        {
                            Id = 10L,
                            Action = "view_all",
                            Code = "ppa.view_all",
                            Description = "Ver todos los PPAs",
                            Module = "ppa"
                        },
                        new
                        {
                            Id = 11L,
                            Action = "view_own",
                            Code = "ppa.view_own",
                            Description = "Ver sus propios PPAs",
                            Module = "ppa"
                        },
                        new
                        {
                            Id = 12L,
                            Action = "create",
                            Code = "ppa.create",
                            Description = "Crear PPAs",
                            Module = "ppa"
                        },
                        new
                        {
                            Id = 13L,
                            Action = "update",
                            Code = "ppa.update",
                            Description = "Actualizar PPAs",
                            Module = "ppa"
                        },
                        new
                        {
                            Id = 14L,
                            Action = "change_status",
                            Code = "ppa.change_status",
                            Description = "Cambiar estado de PPAs",
                            Module = "ppa"
                        },
                        new
                        {
                            Id = 15L,
                            Action = "upload_file",
                            Code = "ppa.upload_file",
                            Description = "Subir archivos a PPAs",
                            Module = "ppa"
                        },
                        new
                        {
                            Id = 16L,
                            Action = "view_all",
                            Code = "resources.view_all",
                            Description = "Ver todos los recursos",
                            Module = "resources"
                        },
                        new
                        {
                            Id = 17L,
                            Action = "view_own",
                            Code = "resources.view_own",
                            Description = "Ver sus propios recursos",
                            Module = "resources"
                        },
                        new
                        {
                            Id = 18L,
                            Action = "create",
                            Code = "resources.create",
                            Description = "Crear recursos",
                            Module = "resources"
                        },
                        new
                        {
                            Id = 19L,
                            Action = "update",
                            Code = "resources.update",
                            Description = "Actualizar recursos",
                            Module = "resources"
                        },
                        new
                        {
                            Id = 20L,
                            Action = "delete",
                            Code = "resources.delete",
                            Description = "Eliminar recursos",
                            Module = "resources"
                        },
                        new
                        {
                            Id = 21L,
                            Action = "view",
                            Code = "dashboard.view",
                            Description = "Ver dashboard",
                            Module = "dashboard"
                        },
                        new
                        {
                            Id = 22L,
                            Action = "view_details",
                            Code = "dashboard.view_details",
                            Description = "Ver detalles del dashboard",
                            Module = "dashboard"
                        });
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.Ppa.PpaAttachmentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("PpaId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FileKey")
                        .IsUnique()
                        .HasDatabaseName("IX_PpaAttachments_FileKey");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_PpaAttachments_IsDeleted");

                    b.HasIndex("PpaId")
                        .HasDatabaseName("IX_PpaAttachments_PpaId");

                    b.HasIndex("Type")
                        .HasDatabaseName("IX_PpaAttachments_Type");

                    b.HasIndex("UploadedByUserId")
                        .HasDatabaseName("IX_PpaAttachments_UploadedByUserId");

                    b.HasIndex("PpaId", "Type")
                        .HasDatabaseName("IX_PpaAttachments_Ppa_Type");

                    b.ToTable("PpaAttachments", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.Ppa.PpaEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AcademicPeriodId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)");

                    b.Property<string>("GeneralObjective")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("PrimaryTeacherId")
                        .HasColumnType("uuid");

                    b.Property<string>("SpecificObjectives")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AcademicPeriodId")
                        .HasDatabaseName("IX_Ppas_AcademicPeriodId");

                    b.HasIndex("PrimaryTeacherId")
                        .HasDatabaseName("IX_Ppas_PrimaryTeacherId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Ppas_Status");

                    b.HasIndex("PrimaryTeacherId", "AcademicPeriodId")
                        .HasDatabaseName("IX_Ppas_Teacher_Period");

                    b.ToTable("Ppas", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.Ppa.PpaTeacherAssignmentEntity", b =>
                {
                    b.Property<Guid>("PpaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeacherAssignmentId")
                        .HasColumnType("uuid");

                    b.HasKey("PpaId", "TeacherAssignmentId");

                    b.HasIndex("PpaId")
                        .HasDatabaseName("IX_PpaTeacherAssignments_PpaId");

                    b.HasIndex("TeacherAssignmentId")
                        .HasDatabaseName("IX_PpaTeacherAssignments_TeacherAssignmentId");

                    b.ToTable("PpaTeacherAssignments", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.RoleEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsSystemRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_Roles_Code");

                    b.HasIndex("IsSystemRole")
                        .HasDatabaseName("IX_Roles_IsSystemRole");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Code = "ADMIN",
                            Description = "Acceso completo a gestión académica (períodos, materias, asignaciones), supervisión de PPAs y dashboard completo.",
                            IsSystemRole = true,
                            Name = "Administrador"
                        },
                        new
                        {
                            Id = 2L,
                            Code = "DOCENTE",
                            Description = "Gestiona sus propios PPAs y recursos académicos, visualiza materias asignadas.",
                            IsSystemRole = true,
                            Name = "Docente"
                        },
                        new
                        {
                            Id = 3L,
                            Code = "CONSULTA_INTERNA",
                            Description = "Acceso de solo lectura para consulta y auditoría de PPAs, recursos y dashboard.",
                            IsSystemRole = true,
                            Name = "Consulta Interna"
                        });
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.RolePermissionEntity", b =>
                {
                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.Property<long>("PermissionId")
                        .HasColumnType("bigint");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId")
                        .HasDatabaseName("IX_RolePermissions_PermissionId");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("IX_RolePermissions_RoleId");

                    b.ToTable("RolePermissions", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 1L
                        },
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 2L
                        },
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 3L
                        },
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 4L
                        },
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 5L
                        },
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 6L
                        },
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 7L
                        },
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 8L
                        },
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 9L
                        },
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 10L
                        },
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 13L
                        },
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 14L
                        },
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 15L
                        },
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 16L
                        },
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 21L
                        },
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 22L
                        },
                        new
                        {
                            RoleId = 2L,
                            PermissionId = 5L
                        },
                        new
                        {
                            RoleId = 2L,
                            PermissionId = 11L
                        },
                        new
                        {
                            RoleId = 2L,
                            PermissionId = 12L
                        },
                        new
                        {
                            RoleId = 2L,
                            PermissionId = 13L
                        },
                        new
                        {
                            RoleId = 2L,
                            PermissionId = 14L
                        },
                        new
                        {
                            RoleId = 2L,
                            PermissionId = 15L
                        },
                        new
                        {
                            RoleId = 2L,
                            PermissionId = 17L
                        },
                        new
                        {
                            RoleId = 2L,
                            PermissionId = 18L
                        },
                        new
                        {
                            RoleId = 2L,
                            PermissionId = 19L
                        },
                        new
                        {
                            RoleId = 2L,
                            PermissionId = 20L
                        },
                        new
                        {
                            RoleId = 3L,
                            PermissionId = 10L
                        },
                        new
                        {
                            RoleId = 3L,
                            PermissionId = 16L
                        },
                        new
                        {
                            RoleId = 3L,
                            PermissionId = 21L
                        });
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Email");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Users_IsActive");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@sigepp.local",
                            IsActive = true,
                            Name = "Administrador SIGEPP",
                            PasswordHash = "$2a$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewY5GyYIr.5gPyOu",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.UserRoleEntity", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("IX_UserRoles_RoleId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_UserRoles_UserId");

                    b.ToTable("UserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000001"),
                            RoleId = 1L
                        });
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.Academics.TeacherAssignmentEntity", b =>
                {
                    b.HasOne("Infrastructure.Persistence.Entities.Academics.AcademicPeriodEntity", "AcademicPeriod")
                        .WithMany("TeacherAssignments")
                        .HasForeignKey("AcademicPeriodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Infrastructure.Persistence.Entities.Academics.SubjectEntity", "Subject")
                        .WithMany("TeacherAssignments")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Infrastructure.Persistence.Entities.UserEntity", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AcademicPeriod");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.Ppa.PpaAttachmentEntity", b =>
                {
                    b.HasOne("Infrastructure.Persistence.Entities.Ppa.PpaEntity", "Ppa")
                        .WithMany("Attachments")
                        .HasForeignKey("PpaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infrastructure.Persistence.Entities.UserEntity", "UploadedBy")
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ppa");

                    b.Navigation("UploadedBy");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.Ppa.PpaEntity", b =>
                {
                    b.HasOne("Infrastructure.Persistence.Entities.Academics.AcademicPeriodEntity", "AcademicPeriod")
                        .WithMany()
                        .HasForeignKey("AcademicPeriodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Infrastructure.Persistence.Entities.UserEntity", "PrimaryTeacher")
                        .WithMany()
                        .HasForeignKey("PrimaryTeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AcademicPeriod");

                    b.Navigation("PrimaryTeacher");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.Ppa.PpaTeacherAssignmentEntity", b =>
                {
                    b.HasOne("Infrastructure.Persistence.Entities.Ppa.PpaEntity", "Ppa")
                        .WithMany("PpaTeacherAssignments")
                        .HasForeignKey("PpaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infrastructure.Persistence.Entities.Academics.TeacherAssignmentEntity", "TeacherAssignment")
                        .WithMany()
                        .HasForeignKey("TeacherAssignmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ppa");

                    b.Navigation("TeacherAssignment");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.RolePermissionEntity", b =>
                {
                    b.HasOne("Infrastructure.Persistence.Entities.PermissionEntity", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infrastructure.Persistence.Entities.RoleEntity", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.UserRoleEntity", b =>
                {
                    b.HasOne("Infrastructure.Persistence.Entities.RoleEntity", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Infrastructure.Persistence.Entities.UserEntity", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.Academics.AcademicPeriodEntity", b =>
                {
                    b.Navigation("TeacherAssignments");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.Academics.SubjectEntity", b =>
                {
                    b.Navigation("TeacherAssignments");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.PermissionEntity", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.Ppa.PpaEntity", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("PpaTeacherAssignments");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.RoleEntity", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.UserEntity", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
