// <auto-generated />
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Infrastructure.Persistence.Entities.PermissionEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_Permissions_Code");

                    b.HasIndex("Module", "Action")
                        .HasDatabaseName("IX_Permissions_Module_Action");

                    b.ToTable("Permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Action = "view",
                            Code = "periods.view",
                            Description = "Ver períodos académicos",
                            Module = "periods"
                        },
                        new
                        {
                            Id = 2L,
                            Action = "create",
                            Code = "periods.create",
                            Description = "Crear períodos académicos",
                            Module = "periods"
                        },
                        new
                        {
                            Id = 3L,
                            Action = "update",
                            Code = "periods.update",
                            Description = "Actualizar períodos académicos",
                            Module = "periods"
                        },
                        new
                        {
                            Id = 4L,
                            Action = "deactivate",
                            Code = "periods.deactivate",
                            Description = "Desactivar períodos académicos",
                            Module = "periods"
                        },
                        new
                        {
                            Id = 5L,
                            Action = "view",
                            Code = "subjects.view",
                            Description = "Ver materias/asignaturas",
                            Module = "subjects"
                        },
                        new
                        {
                            Id = 6L,
                            Action = "create",
                            Code = "subjects.create",
                            Description = "Crear materias/asignaturas",
                            Module = "subjects"
                        },
                        new
                        {
                            Id = 7L,
                            Action = "update",
                            Code = "subjects.update",
                            Description = "Actualizar materias/asignaturas",
                            Module = "subjects"
                        },
                        new
                        {
                            Id = 8L,
                            Action = "deactivate",
                            Code = "subjects.deactivate",
                            Description = "Desactivar materias/asignaturas",
                            Module = "subjects"
                        },
                        new
                        {
                            Id = 9L,
                            Action = "manage",
                            Code = "teacherSubjects.manage",
                            Description = "Gestionar asignación docente-materia",
                            Module = "teacherSubjects"
                        },
                        new
                        {
                            Id = 10L,
                            Action = "view_all",
                            Code = "ppa.view_all",
                            Description = "Ver todos los PPAs",
                            Module = "ppa"
                        },
                        new
                        {
                            Id = 11L,
                            Action = "view_own",
                            Code = "ppa.view_own",
                            Description = "Ver sus propios PPAs",
                            Module = "ppa"
                        },
                        new
                        {
                            Id = 12L,
                            Action = "create",
                            Code = "ppa.create",
                            Description = "Crear PPAs",
                            Module = "ppa"
                        },
                        new
                        {
                            Id = 13L,
                            Action = "update",
                            Code = "ppa.update",
                            Description = "Actualizar PPAs",
                            Module = "ppa"
                        },
                        new
                        {
                            Id = 14L,
                            Action = "change_status",
                            Code = "ppa.change_status",
                            Description = "Cambiar estado de PPAs",
                            Module = "ppa"
                        },
                        new
                        {
                            Id = 15L,
                            Action = "upload_file",
                            Code = "ppa.upload_file",
                            Description = "Subir archivos a PPAs",
                            Module = "ppa"
                        },
                        new
                        {
                            Id = 16L,
                            Action = "view_all",
                            Code = "resources.view_all",
                            Description = "Ver todos los recursos",
                            Module = "resources"
                        },
                        new
                        {
                            Id = 17L,
                            Action = "view_own",
                            Code = "resources.view_own",
                            Description = "Ver sus propios recursos",
                            Module = "resources"
                        },
                        new
                        {
                            Id = 18L,
                            Action = "create",
                            Code = "resources.create",
                            Description = "Crear recursos",
                            Module = "resources"
                        },
                        new
                        {
                            Id = 19L,
                            Action = "update",
                            Code = "resources.update",
                            Description = "Actualizar recursos",
                            Module = "resources"
                        },
                        new
                        {
                            Id = 20L,
                            Action = "delete",
                            Code = "resources.delete",
                            Description = "Eliminar recursos",
                            Module = "resources"
                        },
                        new
                        {
                            Id = 21L,
                            Action = "view",
                            Code = "dashboard.view",
                            Description = "Ver dashboard",
                            Module = "dashboard"
                        },
                        new
                        {
                            Id = 22L,
                            Action = "view_details",
                            Code = "dashboard.view_details",
                            Description = "Ver detalles del dashboard",
                            Module = "dashboard"
                        });
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.RoleEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsSystemRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_Roles_Code");

                    b.HasIndex("IsSystemRole")
                        .HasDatabaseName("IX_Roles_IsSystemRole");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Code = "ADMIN",
                            Description = "Acceso completo a gestión académica (períodos, materias, asignaciones), supervisión de PPAs y dashboard completo.",
                            IsSystemRole = true,
                            Name = "Administrador"
                        },
                        new
                        {
                            Id = 2L,
                            Code = "DOCENTE",
                            Description = "Gestiona sus propios PPAs y recursos académicos, visualiza materias asignadas.",
                            IsSystemRole = true,
                            Name = "Docente"
                        },
                        new
                        {
                            Id = 3L,
                            Code = "CONSULTA_INTERNA",
                            Description = "Acceso de solo lectura para consulta y auditoría de PPAs, recursos y dashboard.",
                            IsSystemRole = true,
                            Name = "Consulta Interna"
                        });
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.RolePermissionEntity", b =>
                {
                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.Property<long>("PermissionId")
                        .HasColumnType("bigint");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId")
                        .HasDatabaseName("IX_RolePermissions_PermissionId");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("IX_RolePermissions_RoleId");

                    b.ToTable("RolePermissions", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 1L
                        },
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 2L
                        },
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 3L
                        },
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 4L
                        },
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 5L
                        },
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 6L
                        },
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 7L
                        },
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 8L
                        },
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 9L
                        },
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 10L
                        },
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 13L
                        },
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 14L
                        },
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 15L
                        },
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 16L
                        },
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 21L
                        },
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 22L
                        },
                        new
                        {
                            RoleId = 2L,
                            PermissionId = 5L
                        },
                        new
                        {
                            RoleId = 2L,
                            PermissionId = 11L
                        },
                        new
                        {
                            RoleId = 2L,
                            PermissionId = 12L
                        },
                        new
                        {
                            RoleId = 2L,
                            PermissionId = 13L
                        },
                        new
                        {
                            RoleId = 2L,
                            PermissionId = 14L
                        },
                        new
                        {
                            RoleId = 2L,
                            PermissionId = 15L
                        },
                        new
                        {
                            RoleId = 2L,
                            PermissionId = 17L
                        },
                        new
                        {
                            RoleId = 2L,
                            PermissionId = 18L
                        },
                        new
                        {
                            RoleId = 2L,
                            PermissionId = 19L
                        },
                        new
                        {
                            RoleId = 2L,
                            PermissionId = 20L
                        },
                        new
                        {
                            RoleId = 3L,
                            PermissionId = 10L
                        },
                        new
                        {
                            RoleId = 3L,
                            PermissionId = 16L
                        },
                        new
                        {
                            RoleId = 3L,
                            PermissionId = 21L
                        });
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.RolePermissionEntity", b =>
                {
                    b.HasOne("Infrastructure.Persistence.Entities.PermissionEntity", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infrastructure.Persistence.Entities.RoleEntity", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.PermissionEntity", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.RoleEntity", b =>
                {
                    b.Navigation("RolePermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
